### ISSUE TITLE
`array argument is not an NSArray` on switch branch

### ISSUE THREAD

**Issue by lajlev** [mathieudutour/git-sketch-plugin#28]
![](https://i.imgur.com/RLzYlHl.png)
2016-05-20 09:22:53.584 sketchtool[6079:429153] Error: caught exception whilst decoding (version 85):**\* -[MSUnarchiver decodeObjectForKey:]: cannot decode object of class (MSImmutableSymbolMaster) for key (NS.object.0); the class may be defined in source code or a library that is not linked
Failed to open document source.sketch -- file:///Users/lajlev/Sites/boligportal/design/projects/160519reate      0x7f92df6cf600lace220Upsell/
((null) MSDocumentDomain:11)

**Comment by mathieudutour** [comment]
Is there some missing fonts on your file or something?

**Comment by marcopellegrini-vodeclic** [comment]
Thank you.
But after configuring > adding new branch > commit > ...

I can't push

<img width="461" alt="capture d ecran 2016-05-23 a 11 35 34" src="https://cloud.githubusercontent.com/assets/17471893/15466761/5f94dc0a-20db-11e6-8576-195516dd8cb9.png">

fatal: The current branch template has no upstream branch.
To push the current branch and set the remote as upstream, use

```
git push --set-upstream origin template
```

**Comment by mathieudutour** [comment]
oh I think it depends of your git config

**Comment by marcopellegrini-vodeclic** [comment]
where I can update my config? via your plugin or other?

**Comment by mathieudutour** [comment]
I updated the plugin so that it will create a new branch on the remote automatically.

Could you try the new version?

**Comment by marcopellegrini-vodeclic** [comment]
Thanks, I updated the plugin..
but I think that after init get repo, it prevents me to go forward
<img width="423" alt="capture d ecran 2016-05-23 a 12 16 44" src="https://cloud.githubusercontent.com/assets/17471893/15467792/9a0704e4-20e0-11e6-9386-45f7f77cab7f.png">

**Comment by mathieudutour** [comment]
Yes, it's because you haven't stored your github credentials yet

Follow this guide to fix it: https://help.github.com/articles/caching-your-github-password-in-git/

**Comment by marcopellegrini-vodeclic** [comment]
Thanks Mathieu, I had problems with https because I was connecting to git via SSH...
For now, after caching password + cloning a project via the terminal (for testing my connection) the push is working...

But I still have a few problems with this plugin:
1) the "switch branch" is not working
<img width="418" alt="capture d ecran 2016-05-23 a 14 47 10" src="https://cloud.githubusercontent.com/assets/17471893/15471300/8e9ffbc8-20f5-11e6-8fe4-e16f2f7810f6.png">
**\* -[NSMutableArray addObjectsFromArray:]: array argument is not an NSArray
2) since I need to see what is happening with branches pulls etc., if I want to launch the terminal via the plugin, sketch crashes :(

**Comment by mathieudutour** [comment]
Oh I broke it to fix another issue. Should be fix with the new changes I just pushed (opening the terminal)

**Comment by marcopellegrini-vodeclic** [comment]
cool, now terminal is working...
what about the "switch branch" (that isn't working)? 
and actually it needs to install xcode?

**Comment by mathieudutour** [comment]
what does `git branch` and `git branch | awk -F ' +' '! /\(no branch\)/ {print $2}'` return?

**Comment by marcopellegrini-vodeclic** [comment]
it return always <img width="418" alt="capture d ecran 2016-05-23 a 14 47 10" src="https://cloud.githubusercontent.com/assets/17471893/15471300/8e9ffbc8-20f5-11e6-8fe4-e16f2f7810f6.png">

**Comment by mathieudutour** [comment]
I mean if you type those command in a terminal?

**Comment by marcopellegrini-vodeclic** [comment]
<img width="571" alt="capture d ecran 2016-05-24 a 18 35 57" src="https://cloud.githubusercontent.com/assets/17471893/15512066/66216ba2-21de-11e6-84ad-93e233e431ed.png">
it returns the good list of branches

**Comment by mathieudutour** [comment]
hum weird... I'll try to look more into it

**Comment by mathieudutour** [comment]
should be fix in the new release. I have a weird prefix on the first branch though: `(B[m`. Do you see it as well?
